// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpLcLNr1GYLusFsrbzHJTaA6iQ0jqLh4w',
    appId: '1:762812636425:web:d005d879cb6686ac9247d8',
    messagingSenderId: '762812636425',
    projectId: 'shopsmart-32525',
    authDomain: 'shopsmart-32525.firebaseapp.com',
    storageBucket: 'shopsmart-32525.appspot.com',
    measurementId: 'G-4BXPP9W5FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGLA5QXWkOpFsQ_3I7Ec1_bBHO5cOi0k',
    appId: '1:762812636425:android:e71e54acb1f75e989247d8',
    messagingSenderId: '762812636425',
    projectId: 'shopsmart-32525',
    storageBucket: 'shopsmart-32525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhf6PScaxAGOzVg-0_QKUnjDVeTovTkpY',
    appId: '1:762812636425:ios:6a9e112b0193e28f9247d8',
    messagingSenderId: '762812636425',
    projectId: 'shopsmart-32525',
    storageBucket: 'shopsmart-32525.appspot.com',
    iosClientId: '762812636425-qhshs34v8a36f6gc506pshjcgslneijb.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhf6PScaxAGOzVg-0_QKUnjDVeTovTkpY',
    appId: '1:762812636425:ios:2159db248cd018229247d8',
    messagingSenderId: '762812636425',
    projectId: 'shopsmart-32525',
    storageBucket: 'shopsmart-32525.appspot.com',
    iosClientId: '762812636425-4kkgnggknfq04eardlisp3amhtnj574m.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmart.RunnerTests',
  );
}
